config/routes.rb
Problem1::Application.routes.draw do
  root to: 'static_pages#home'
  match( '/help', to: 'static_pages#help', via: 'get' )
  match( '/about', to: 'static_pages#about', via: 'get' )
  match( '/contact', to: 'static_pages#contact', via: 'get' )
  match( '/problem1', to: 'static_pages#problem1', via: 'get' )
  match( '/problem2', to: 'static_pages#problem2', via: 'get' )
  match( '/problem3', to: 'static_pages#problem3', via: 'get' )
  match( '/problem4', to: 'static_pages#problem4', via: 'get' )
end

app/models/static_page.rb
class StaticPage
  class << self
    def palindrome( number )
      number_string = number.to_s
      reverse_number_string = number_string.reverse
      ((number_string <=> reverse_number_string) == 0) ? true : false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
require 'prime'

class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def problem1
    @answer = 0
    @multiples = Array.new
    for i in 1 .. params[:max].to_i - 1
      if ((i % 3 == 0) && (i % 5 == 0))
        @multiples.push( i )
      elsif (i % 3 == 0)
        @multiples.push( i )
      elsif (i % 5 == 0)
        @multiples.push( i )
      end
    end
    @multiples.each do |n|
      @answer += n
    end
  end

  def problem2
    @answer = 0
    penultimate = 1
    ultimate = 1
    fibanacci = 2
    while (fibanacci < params[:max].to_i)
      fibanacci = penultimate + ultimate
      penultimate = ultimate
      ultimate = fibanacci
      if (fibanacci % 2 == 0) then @answer += fibanacci end
    end
  end

  def problem3
    @answer = 0
    Prime.each( Math.sqrt( params[:max].to_i ) ) do |prime|
      if (params[:max].to_i % prime == 0) then @answer = prime end
    end
  end

  def problem4
    @answer = 0
    for i in 1 .. params[:max].to_i
      for j in 1 .. params[:max].to_i
        product = i * j
        if ((product > @answer) && StaticPage.palindrome( product )) then
          @answer = product
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Solutions to <a href="http://projecteuler.net">Project Euler</a> problems 
    by Andrew Dixon
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to( "sample app", root_path, id: "logo" ) %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to( "Home", root_path ) %></li>
          <li><%= link_to( "Help", help_path ) %></li>
          <li><%= link_to( "Sign in", '#' ) %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html> <html>
<head>
  <title>Project Euler | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render( 'layouts/header' ) %>
  <div class = 'container'>
    <%= yield %>
    <%= render( 'layouts/footer' ) %>
  </div>  
</body>
</html>

app/views/static_pages/_problem.html.erb
<div class = "center hero-unit" >
  <h1><%= yield( :title ) %></h1>
  <%= yield( :examples ) %>

  <h2><%= yield( :problem_statement ) %></h2>
  <%= form_tag( { :controller => 'static_pages', :action => yield( :action ) }, 
    :method => 'get' ) do %>
    <%= text_field_tag( :max, 'max number' ) %><br>
  <% end %>
  <% if (@answer > 0) %>
    <%= yield( :answer_label ) %><%= @answer %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<% provide( :title, 'Contact' ) %>
<h1>Contact Page</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title,  'Home') %>

<div class = "center hero-unit">
  <h1>Project Euler</h1>
  <h2>Solutions to some Wicked Cool Problems</h2>
  <%= link_to "Sign Up Now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/problem1.html.erb
<% provide( :title, 'Problem 1' ) %>

<div class = "center hero-unit" >
  <h1>Problem 1</h1>
  If we list all the natural numbers below 10 that are multiples of 3 or 5, 
  we get 3, 5, 6 and 9.<br>
  The sum of these multiples is 23.

  <h2>Find the sum of all the multiples of 3 or 5 below 1000.</h2>
  <%= form_tag( { :controller => 'static_pages', :action => 'problem1' }, 
    :method => 'get' ) do %>
    <%= text_field_tag( :max, 'max number' ) %><br>
  <% end %>
  <% if (@answer > 0) %>
    Sum of Multiples: <%= @answer %>
  <% end %>
</div>

app/views/static_pages/problem2.html.erb
<% 
  provide( :title, 'Problem 2' ) 
  provide( :action, 'problem2' )
  provide( :examples, 
           'Each new term in the Fibonacci sequence is generated by adding the 
            previous two terms. By starting with 1 and 2, the first 10 terms will 
            be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...' ) 
  provide( :problem_statement,
           'By considering the terms in the Fibonacci sequence whose values do 
            not exceed four million, find the sum of the even-valued terms.' ) 
  provide( :answer_label,
           'Sum of Even Fibinacci Numbers:' )
%>
<%= render( 'problem' ) %>

app/views/static_pages/problem3.html.erb
<% 
  provide( :title, 'Problem 3' ) 
  provide( :action, 'problem3' )
  provide( :examples, 
           'The prime factors of 13195 are 5, 7, 13 and 29.' ) 
  provide( :problem_statement,
           'What is the largest prime factor of the number 600851475143 ?' ) 
  provide( :answer_label,
           'Largest Prime Factor:' )
%>
<%= render( 'problem' ) %>

app/views/static_pages/problem4.html.erb
<% 
  provide( :title, 'Problem 4' ) 
  provide( :action, 'problem4' )
  provide( :examples,
           'A palindromic number reads the same both ways. The largest palindrome 
            made from the product of two 2-digit numbers is 9009 = 91 99.' )
  provide( :problem_statement,
           'Find the largest palindrome made from the product of two 3-digit 
            numbers.' )
  provide( :answer_label,
           'Largest Palindrome:' )
%>
<%= render( 'problem' ) %>